# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeRe_RenameBox.ui'
#
# Created: Wed Jan 22 17:21:28 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(606, 443)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txt_remove = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_remove.sizePolicy().hasHeightForWidth())
        self.txt_remove.setSizePolicy(sizePolicy)
        self.txt_remove.setObjectName("txt_remove")
        self.verticalLayout_3.addWidget(self.txt_remove)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(17, 104, 392, 72))
        self.groupBox.setObjectName("groupBox")
        self.rb_nr_beginning = QtGui.QRadioButton(self.groupBox)
        self.rb_nr_beginning.setGeometry(QtCore.QRect(0, 20, 105, 21))
        self.rb_nr_beginning.setChecked(True)
        self.rb_nr_beginning.setObjectName("rb_nr_beginning")
        self.rb_nr_ending = QtGui.QRadioButton(self.groupBox)
        self.rb_nr_ending.setGeometry(QtCore.QRect(120, 20, 105, 21))
        self.rb_nr_ending.setObjectName("rb_nr_ending")
        self.layoutWidget = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(17, 25, 261, 63))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_addNmbrs = QtGui.QCheckBox(self.layoutWidget)
        self.rb_addNmbrs.setChecked(True)
        self.rb_addNmbrs.setObjectName("rb_addNmbrs")
        self.horizontalLayout_2.addWidget(self.rb_addNmbrs)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txt_startnmbr = QtGui.QLineEdit(self.groupBox_6)
        self.txt_startnmbr.setObjectName("txt_startnmbr")
        self.verticalLayout_4.addWidget(self.txt_startnmbr)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_custom = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_custom.sizePolicy().hasHeightForWidth())
        self.txt_custom.setSizePolicy(sizePolicy)
        self.txt_custom.setObjectName("txt_custom")
        self.verticalLayout.addWidget(self.txt_custom)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_txt_beginning = QtGui.QRadioButton(self.groupBox_3)
        self.rb_txt_beginning.setChecked(True)
        self.rb_txt_beginning.setObjectName("rb_txt_beginning")
        self.horizontalLayout.addWidget(self.rb_txt_beginning)
        self.rb_txt_ending = QtGui.QRadioButton(self.groupBox_3)
        self.rb_txt_ending.setObjectName("rb_txt_ending")
        self.horizontalLayout.addWidget(self.rb_txt_ending)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lW_source = QtGui.QListWidget(Dialog)
        self.lW_source.setObjectName("lW_source")
        self.verticalLayout_5.addWidget(self.lW_source)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pB_preview = QtGui.QPushButton(Dialog)
        self.pB_preview.setObjectName("pB_preview")
        self.horizontalLayout_3.addWidget(self.pB_preview)
        self.pB_iterate = QtGui.QPushButton(Dialog)
        self.pB_iterate.setObjectName("pB_iterate")
        self.horizontalLayout_3.addWidget(self.pB_iterate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.lW_result = QtGui.QListWidget(Dialog)
        self.lW_result.setObjectName("lW_result")
        self.verticalLayout_5.addWidget(self.lW_result)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "remove Substrings (seperator ;)", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_remove.setText(QtGui.QApplication.translate("Dialog", "<allNumbers>; ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "add numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "add to:", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_nr_beginning.setText(QtGui.QApplication.translate("Dialog", "beginning", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_nr_ending.setText(QtGui.QApplication.translate("Dialog", "ending", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_addNmbrs.setText(QtGui.QApplication.translate("Dialog", "Add Nmbrs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "startnumber", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_startnmbr.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "add custom txt:", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_custom.setText(QtGui.QApplication.translate("Dialog", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "add to:", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_txt_beginning.setText(QtGui.QApplication.translate("Dialog", "beginning", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_txt_ending.setText(QtGui.QApplication.translate("Dialog", "ending", None, QtGui.QApplication.UnicodeUTF8))
        self.pB_preview.setText(QtGui.QApplication.translate("Dialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.pB_iterate.setText(QtGui.QApplication.translate("Dialog", "Iterate!", None, QtGui.QApplication.UnicodeUTF8))

